// Generated by tool/glyphs.py; edit the icons there and run it again.

import 'dart:math';

import 'package:flutter/widgets.dart';

/// The app's own icons, drawn on a 24-unit grid: a soft tinted body, one
/// stroke weight and solid dots, so they read as one set. Painted on the
/// canvas, never loaded as images.
enum Glyph {
  home,
  food,
  travel,
  bag,
  subscription,
  other,
  salary,
  payout,
  income,
  dividend,
  cup,
  shirt,
  gift,
  book,
  health,
  pet,
  car,
  game,
  transfer,
  investment,
  cash,
  bank,
  phone,
  card,
  coins,
  safe,
  suitcase,
  briefcase,
  chat,
  store,
  scan,
  ticket,
  overview,
  records,
  wallet,
  reports,
  budget,
  recurring,
  categories,
  sliders,
  add,
  back,
  next,
  arrow,
  close,
  search,
  download,
  edit,
  calendar,
  note,
  eye,
  eyeOff,
  calculator,
  backspace,
  reset,
}

/// A [Glyph] at [size], in [color] or the surrounding icon colour. With
/// [tinted] off only the strokes and dots are drawn.
class GlyphIcon extends StatelessWidget {
  const GlyphIcon(
    this.glyph, {
    super.key,
    this.size = 22,
    this.color,
    this.weight = 1.6,
    this.tinted = true,
  });

  final Glyph glyph;
  final double size;
  final Color? color;

  /// Stroke width in logical pixels.
  final double weight;
  final bool tinted;

  @override
  Widget build(BuildContext context) {
    final ink = color ?? IconTheme.of(context).color ?? const Color(0xFF344638);
    // Like Icon, keep the drawn size when the parent asks for more room.
    return Center(
      widthFactor: 1,
      heightFactor: 1,
      child: SizedBox.square(
        dimension: size,
        child: CustomPaint(
          painter: GlyphPainter(glyph, ink, weight, tinted: tinted),
        ),
      ),
    );
  }
}

class GlyphPainter extends CustomPainter {
  const GlyphPainter(this.glyph, this.color, this.weight, {this.tinted = true});

  final Glyph glyph;
  final Color color;
  final double weight;
  final bool tinted;

  @override
  void paint(Canvas canvas, Size size) {
    final scale = size.shortestSide / 24;
    if (scale <= 0) return;
    final (tint, line, solid) = _paths[glyph] ??= _build(glyph);
    canvas
      ..save()
      ..translate((size.width - 24 * scale) / 2, (size.height - 24 * scale) / 2)
      ..scale(scale);
    if (tinted) {
      canvas.drawPath(tint, Paint()..color = color.withValues(alpha: 0.28));
    }
    canvas
      ..drawPath(
        line,
        Paint()
          ..style = PaintingStyle.stroke
          ..strokeWidth = weight / scale
          ..strokeCap = StrokeCap.round
          ..strokeJoin = StrokeJoin.round
          ..color = color,
      )
      ..drawPath(solid, Paint()..color = color)
      ..restore();
  }

  @override
  bool shouldRepaint(GlyphPainter old) =>
      old.glyph != glyph ||
      old.color != color ||
      old.weight != weight ||
      old.tinted != tinted;
}

/// Each glyph's paths, built once on the 24-unit grid and reused by every
/// icon that shows it.
final _paths = <Glyph, (Path, Path, Path)>{};

(Path, Path, Path) _build(Glyph glyph) {
  final tint = Path();
  final line = Path();
  final solid = Path();
  _draw(glyph, tint, line, solid);
  return (tint, line, solid);
}

void _poly(Path p, List<double> xy, {bool close = false}) {
  p.moveTo(xy[0], xy[1]);
  for (var i = 2; i < xy.length; i += 2) {
    p.lineTo(xy[i], xy[i + 1]);
  }
  if (close) p.close();
}

void _box(Path p, double l, double t, double r, double b, double radius) {
  p.addRRect(RRect.fromLTRBR(l, t, r, b, Radius.circular(radius)));
}

void _ring(Path p, double x, double y, double r) {
  p.addOval(Rect.fromCircle(center: Offset(x, y), radius: r));
}

void _arc(Path p, double x, double y, double r, double from, double sweep) {
  p.addArc(
    Rect.fromCircle(center: Offset(x, y), radius: r),
    from * pi / 180,
    sweep * pi / 180,
  );
}

void _arcTo(Path p, double x, double y, double r, double from, double sweep) {
  p.arcTo(
    Rect.fromCircle(center: Offset(x, y), radius: r),
    from * pi / 180,
    sweep * pi / 180,
    false,
  );
}

void _draw(Glyph glyph, Path t, Path p, Path f) {
  switch (glyph) {
    case Glyph.home:
      _poly(t, [6, 10, 12, 5, 18, 10, 18, 19.5, 6, 19.5], close: true);
      _poly(p, [3.5, 11.5, 12, 4.2, 20.5, 11.5]);
      _poly(p, [6, 9.8, 6, 19.5, 18, 19.5, 18, 9.8]);
      _poly(p, [10, 19.5, 10, 14.5, 14, 14.5, 14, 19.5]);
    case Glyph.food:
      t.moveTo(4, 12);
      t.lineTo(20, 12);
      _arcTo(t, 12, 12, 8, 0, 180);
      t.close();
      p.moveTo(4, 12);
      p.lineTo(20, 12);
      _arcTo(p, 12, 12, 8, 0, 180);
      p.close();
      _poly(p, [13.5, 9.5, 19, 3.5]);
      _poly(p, [10.5, 9.5, 15, 3.5]);
    case Glyph.travel:
      _box(t, 5, 4, 19, 17, 3);
      _box(p, 5, 4, 19, 17, 3);
      _poly(p, [5, 10.5, 19, 10.5]);
      _poly(p, [9.5, 6.8, 14.5, 6.8]);
      _poly(p, [8, 17, 8, 20]);
      _poly(p, [16, 17, 16, 20]);
      _ring(f, 8.5, 13.8, 1.1);
      _ring(f, 15.5, 13.8, 1.1);
    case Glyph.bag:
      _box(t, 4.5, 8, 19.5, 20.5, 2.5);
      _box(p, 4.5, 8, 19.5, 20.5, 2.5);
      p.moveTo(8.5, 11);
      p.lineTo(8.5, 7);
      _arcTo(p, 12, 7, 3.5, 180, 180);
      p.lineTo(15.5, 11);
    case Glyph.subscription:
      _box(t, 4, 5.5, 20, 10, 2.5);
      _box(p, 4, 5.5, 20, 20, 2.5);
      _poly(p, [4, 10, 20, 10]);
      _poly(p, [8.5, 3.5, 8.5, 7]);
      _poly(p, [15.5, 3.5, 15.5, 7]);
      _poly(p, [9, 15, 11, 17, 15, 13]);
    case Glyph.other:
      _ring(f, 6, 12, 1.5);
      _ring(f, 12, 12, 1.5);
      _ring(f, 18, 12, 1.5);
    case Glyph.salary:
      _box(t, 3, 8.5, 18.5, 18, 2);
      _poly(p, [6.5, 8.5, 6.5, 5.5, 21, 5.5, 21, 15, 18.5, 15]);
      _box(p, 3, 8.5, 18.5, 18, 2);
      _ring(p, 10.75, 13.25, 2.3);
      _ring(f, 6.2, 13.25, 0.9);
      _ring(f, 15.3, 13.25, 0.9);
    case Glyph.payout:
      t.moveTo(6, 3.5);
      t.lineTo(18, 3.5);
      t.lineTo(18, 20.5);
      t.lineTo(16, 19);
      t.lineTo(14, 20.5);
      t.lineTo(12, 19);
      t.lineTo(10, 20.5);
      t.lineTo(8, 19);
      t.lineTo(6, 20.5);
      t.close();
      p.moveTo(6, 3.5);
      p.lineTo(18, 3.5);
      p.lineTo(18, 20.5);
      p.lineTo(16, 19);
      p.lineTo(14, 20.5);
      p.lineTo(12, 19);
      p.lineTo(10, 20.5);
      p.lineTo(8, 19);
      p.lineTo(6, 20.5);
      p.close();
      _poly(p, [9, 8, 15, 8]);
      _poly(p, [9, 11.5, 15, 11.5]);
      _poly(p, [9, 15, 12.5, 15]);
    case Glyph.income:
      t.moveTo(9, 9);
      t.quadraticBezierTo(4, 12.5, 4.5, 16.5);
      t.quadraticBezierTo(5, 20.5, 12, 20.5);
      t.quadraticBezierTo(19, 20.5, 19.5, 16.5);
      t.quadraticBezierTo(20, 12.5, 15, 9);
      t.close();
      p.moveTo(9, 9);
      p.quadraticBezierTo(4, 12.5, 4.5, 16.5);
      p.quadraticBezierTo(5, 20.5, 12, 20.5);
      p.quadraticBezierTo(19, 20.5, 19.5, 16.5);
      p.quadraticBezierTo(20, 12.5, 15, 9);
      p.close();
      p.moveTo(9, 9);
      p.lineTo(7.5, 4.5);
      p.quadraticBezierTo(12, 6, 16.5, 4.5);
      p.lineTo(15, 9);
      _poly(p, [12, 12.5, 12, 17.5]);
      _poly(p, [9.5, 15, 14.5, 15]);
    case Glyph.dividend:
      _ring(t, 12, 15.5, 5);
      t.moveTo(12, 8);
      t.quadraticBezierTo(7.5, 8.3, 7, 4);
      t.quadraticBezierTo(11.5, 4, 12, 8);
      t.close();
      _ring(p, 12, 15.5, 5);
      _poly(p, [12, 10.5, 12, 7.5]);
      p.moveTo(12, 8);
      p.quadraticBezierTo(7.5, 8.3, 7, 4);
      p.quadraticBezierTo(11.5, 4, 12, 8);
      p.moveTo(12, 7.5);
      p.quadraticBezierTo(15.2, 7.3, 16.5, 4.5);
      p.quadraticBezierTo(13, 4.3, 12, 7.5);
      _ring(f, 12, 15.5, 1.3);
    case Glyph.cup:
      t.moveTo(5, 8);
      t.lineTo(16, 8);
      t.lineTo(15, 18);
      t.quadraticBezierTo(14.8, 20, 13, 20);
      t.lineTo(8, 20);
      t.quadraticBezierTo(6.2, 20, 6, 18);
      t.close();
      p.moveTo(5, 8);
      p.lineTo(16, 8);
      p.lineTo(15, 18);
      p.quadraticBezierTo(14.8, 20, 13, 20);
      p.lineTo(8, 20);
      p.quadraticBezierTo(6.2, 20, 6, 18);
      p.close();
      p.moveTo(15.8, 10);
      p.quadraticBezierTo(19.5, 9.8, 19.3, 12.6);
      p.quadraticBezierTo(19, 15.3, 15.3, 15.3);
      _poly(p, [9, 5.5, 9, 3.5]);
      _poly(p, [12.5, 5.5, 12.5, 3.5]);
    case Glyph.shirt:
      _poly(t, [
        8, 4, 4, 6.5, 5.5, 10.5, 7.5, 9.5, 7.5, 20, 16.5, 20, 16.5, 9.5, 18.5,
        10.5, 20, 6.5, 16, 4,
      ], close: true);
      p.moveTo(8, 4);
      p.lineTo(4, 6.5);
      p.lineTo(5.5, 10.5);
      p.lineTo(7.5, 9.5);
      p.lineTo(7.5, 20);
      p.lineTo(16.5, 20);
      p.lineTo(16.5, 9.5);
      p.lineTo(18.5, 10.5);
      p.lineTo(20, 6.5);
      p.lineTo(16, 4);
      p.quadraticBezierTo(14.5, 6.5, 12, 6.5);
      p.quadraticBezierTo(9.5, 6.5, 8, 4);
      p.close();
    case Glyph.gift:
      _box(t, 5, 10.5, 19, 20, 1.5);
      _box(p, 3.5, 7, 20.5, 10.5, 1.5);
      _poly(p, [5, 10.5, 5, 20, 19, 20, 19, 10.5]);
      _poly(p, [12, 7, 12, 20]);
      p.moveTo(12, 7);
      p.quadraticBezierTo(8, 2.5, 7.5, 5.3);
      p.quadraticBezierTo(7.5, 7, 12, 7);
      p.moveTo(12, 7);
      p.quadraticBezierTo(16, 2.5, 16.5, 5.3);
      p.quadraticBezierTo(16.5, 7, 12, 7);
    case Glyph.book:
      t.moveTo(12, 6.5);
      t.quadraticBezierTo(8, 4.5, 4, 5.5);
      t.lineTo(4, 18.5);
      t.quadraticBezierTo(8, 17.5, 12, 19.5);
      t.quadraticBezierTo(16, 17.5, 20, 18.5);
      t.lineTo(20, 5.5);
      t.quadraticBezierTo(16, 4.5, 12, 6.5);
      t.close();
      p.moveTo(12, 6.5);
      p.quadraticBezierTo(8, 4.5, 4, 5.5);
      p.lineTo(4, 18.5);
      p.quadraticBezierTo(8, 17.5, 12, 19.5);
      p.quadraticBezierTo(16, 17.5, 20, 18.5);
      p.lineTo(20, 5.5);
      p.quadraticBezierTo(16, 4.5, 12, 6.5);
      p.close();
      _poly(p, [12, 6.5, 12, 19.5]);
    case Glyph.health:
      t.moveTo(12, 19.5);
      t.quadraticBezierTo(4, 14, 4, 9.5);
      t.quadraticBezierTo(4, 5.5, 8, 5.5);
      t.quadraticBezierTo(10.5, 5.5, 12, 8);
      t.quadraticBezierTo(13.5, 5.5, 16, 5.5);
      t.quadraticBezierTo(20, 5.5, 20, 9.5);
      t.quadraticBezierTo(20, 14, 12, 19.5);
      t.close();
      p.moveTo(12, 19.5);
      p.quadraticBezierTo(4, 14, 4, 9.5);
      p.quadraticBezierTo(4, 5.5, 8, 5.5);
      p.quadraticBezierTo(10.5, 5.5, 12, 8);
      p.quadraticBezierTo(13.5, 5.5, 16, 5.5);
      p.quadraticBezierTo(20, 5.5, 20, 9.5);
      p.quadraticBezierTo(20, 14, 12, 19.5);
      p.close();
      _poly(p, [12, 10, 12, 15]);
      _poly(p, [9.5, 12.5, 14.5, 12.5]);
    case Glyph.pet:
      _ring(t, 12, 15.5, 4.2);
      _ring(p, 12, 15.5, 4.2);
      _ring(f, 6, 11, 1.9);
      _ring(f, 9.3, 6.8, 1.9);
      _ring(f, 14.7, 6.8, 1.9);
      _ring(f, 18, 11, 1.9);
    case Glyph.car:
      _poly(t, [
        3.5, 16, 3.5, 11.5, 6.5, 11.5, 8.5, 6.5, 15.5, 6.5, 17.5, 11.5, 20.5,
        11.5, 20.5, 16,
      ], close: true);
      p.moveTo(3.5, 16);
      p.lineTo(3.5, 12.5);
      p.quadraticBezierTo(3.5, 11.5, 4.5, 11.5);
      p.lineTo(6.5, 11.5);
      p.lineTo(8.5, 6.5);
      p.lineTo(15.5, 6.5);
      p.lineTo(17.5, 11.5);
      p.lineTo(19.5, 11.5);
      p.quadraticBezierTo(20.5, 11.5, 20.5, 12.5);
      p.lineTo(20.5, 16);
      p.close();
      _poly(p, [12, 6.5, 12, 11.5]);
      _ring(f, 7.5, 18, 2);
      _ring(f, 16.5, 18, 2);
    case Glyph.game:
      _box(t, 3, 8, 21, 17, 4.5);
      _box(p, 3, 8, 21, 17, 4.5);
      _poly(p, [7.5, 10.8, 7.5, 14.2]);
      _poly(p, [5.8, 12.5, 9.2, 12.5]);
      _ring(f, 15.3, 11.3, 1.1);
      _ring(f, 17.5, 13.6, 1.1);
    case Glyph.transfer:
      _poly(p, [5, 8.5, 19, 8.5]);
      _poly(p, [15.5, 5, 19, 8.5, 15.5, 12]);
      _poly(p, [19, 15.5, 5, 15.5]);
      _poly(p, [8.5, 12, 5, 15.5, 8.5, 19]);
    case Glyph.investment:
      _poly(t, [4, 17, 9, 12, 13, 15, 20, 7.5, 20, 20, 4, 20], close: true);
      _poly(p, [4, 17, 9, 12, 13, 15, 20, 7.5]);
      _poly(p, [15.5, 7.5, 20, 7.5, 20, 12]);
    case Glyph.cash:
      _box(t, 3, 6.5, 21, 17.5, 2.5);
      _box(p, 3, 6.5, 21, 17.5, 2.5);
      _ring(p, 12, 12, 2.7);
      _ring(f, 6.5, 12, 1);
      _ring(f, 17.5, 12, 1);
    case Glyph.bank:
      _poly(t, [3.5, 9.5, 12, 4.5, 20.5, 9.5], close: true);
      _poly(p, [3.5, 9.5, 12, 4.5, 20.5, 9.5], close: true);
      _poly(p, [7, 12.5, 7, 17]);
      _poly(p, [12, 12.5, 12, 17]);
      _poly(p, [17, 12.5, 17, 17]);
      _poly(p, [4, 20, 20, 20]);
    case Glyph.phone:
      _box(t, 7, 3, 17, 21, 2.5);
      _box(p, 7, 3, 17, 21, 2.5);
      _poly(p, [10.5, 18, 13.5, 18]);
    case Glyph.card:
      _box(t, 3, 6, 21, 10, 2.5);
      _box(p, 3, 6, 21, 18, 2.5);
      _poly(p, [3, 10, 21, 10]);
      _poly(p, [6.5, 14.5, 10, 14.5]);
    case Glyph.coins:
      _ring(t, 8.5, 9, 4.5);
      _box(t, 10.5, 14.5, 20.5, 21, 1.75);
      _ring(p, 8.5, 9, 4.5);
      _box(p, 10.5, 14.5, 20.5, 17.75, 1.6);
      _box(p, 10.5, 17.75, 20.5, 21, 1.6);
    case Glyph.safe:
      _box(t, 4, 4, 20, 19, 2.5);
      _box(p, 4, 4, 20, 19, 2.5);
      _ring(p, 12, 11.5, 3.5);
      _poly(p, [7.5, 19, 7.5, 21]);
      _poly(p, [16.5, 19, 16.5, 21]);
      _ring(f, 12, 11.5, 1);
    case Glyph.suitcase:
      _box(t, 5, 7, 19, 20, 2.5);
      _box(p, 5, 7, 19, 20, 2.5);
      _poly(p, [9.5, 7, 9.5, 4.5, 14.5, 4.5, 14.5, 7]);
      _poly(p, [9, 10.5, 9, 16.5]);
      _poly(p, [15, 10.5, 15, 16.5]);
    case Glyph.briefcase:
      _box(t, 3.5, 8, 20.5, 19.5, 2.5);
      _box(p, 3.5, 8, 20.5, 19.5, 2.5);
      _poly(p, [9, 8, 9, 5, 15, 5, 15, 8]);
      _poly(p, [3.5, 13, 20.5, 13]);
    case Glyph.chat:
      _box(t, 4, 5, 20, 16.5, 3);
      _box(p, 4, 5, 20, 16.5, 3);
      _poly(p, [8, 16.5, 8, 20, 12, 16.5]);
      _ring(f, 9, 10.75, 1);
      _ring(f, 12, 10.75, 1);
      _ring(f, 15, 10.75, 1);
    case Glyph.store:
      _poly(t, [4, 9.5, 5.5, 4.5, 18.5, 4.5, 20, 9.5], close: true);
      _poly(p, [4, 9.5, 5.5, 4.5, 18.5, 4.5, 20, 9.5], close: true);
      _poly(p, [5.5, 9.5, 5.5, 19.5, 18.5, 19.5, 18.5, 9.5]);
      _poly(p, [10, 19.5, 10, 15, 14, 15, 14, 19.5]);
    case Glyph.scan:
      _box(t, 7.5, 7.5, 16.5, 16.5, 2);
      _poly(p, [4, 8, 4, 4, 8, 4]);
      _poly(p, [16, 4, 20, 4, 20, 8]);
      _poly(p, [20, 16, 20, 20, 16, 20]);
      _poly(p, [8, 20, 4, 20, 4, 16]);
      _poly(p, [6.5, 12, 17.5, 12]);
    case Glyph.ticket:
      _box(t, 3.5, 6.5, 20.5, 17.5, 2.5);
      _box(p, 3.5, 6.5, 20.5, 17.5, 2.5);
      _poly(p, [14.5, 9, 14.5, 10.3]);
      _poly(p, [14.5, 11.4, 14.5, 12.7]);
      _poly(p, [14.5, 13.8, 14.5, 15]);
    case Glyph.overview:
      _box(t, 4, 4, 10.5, 12, 1.8);
      _box(p, 4, 4, 10.5, 12, 1.8);
      _box(p, 13.5, 4, 20, 8.5, 1.8);
      _box(p, 13.5, 11.5, 20, 20, 1.8);
      _box(p, 4, 15, 10.5, 20, 1.8);
    case Glyph.records:
      _box(t, 5, 3.5, 19, 20.5, 2.5);
      _box(p, 5, 3.5, 19, 20.5, 2.5);
      _poly(p, [8.5, 8.5, 15.5, 8.5]);
      _poly(p, [8.5, 12, 15.5, 12]);
      _poly(p, [8.5, 15.5, 12.5, 15.5]);
    case Glyph.wallet:
      _box(t, 3.5, 6.5, 20.5, 19.5, 2.5);
      _box(p, 3.5, 6.5, 20.5, 19.5, 2.5);
      _poly(p, [6, 6.5, 15, 3.8, 16, 6.5]);
      _box(p, 14, 10.5, 20.5, 15, 1.6);
      _ring(f, 16.6, 12.75, 0.95);
    case Glyph.reports:
      _box(t, 5.5, 12, 8.5, 19, 1);
      _box(t, 10.5, 6, 13.5, 19, 1);
      _box(t, 15.5, 9.5, 18.5, 19, 1);
      _box(p, 5.5, 12, 8.5, 19, 1);
      _box(p, 10.5, 6, 13.5, 19, 1);
      _box(p, 15.5, 9.5, 18.5, 19, 1);
      _poly(p, [3.5, 20.5, 20.5, 20.5]);
    case Glyph.budget:
      t.moveTo(12, 12);
      t.lineTo(12, 4);
      _arcTo(t, 12, 12, 8, 270, 120);
      t.close();
      _ring(p, 12, 12, 8);
      _poly(p, [12, 4, 12, 12, 18.93, 16]);
    case Glyph.recurring:
      _arc(p, 12, 12, 7, 200, 130);
      _poly(p, [18.4, 4.9, 18.1, 8.5, 14.6, 8.1]);
      _arc(p, 12, 12, 7, 20, 130);
      _poly(p, [5.6, 19.1, 5.9, 15.5, 9.4, 15.9]);
    case Glyph.categories:
      _box(t, 4, 4, 10.5, 10.5, 1.8);
      _box(p, 4, 4, 10.5, 10.5, 1.8);
      _box(p, 13.5, 4, 20, 10.5, 1.8);
      _box(p, 4, 13.5, 10.5, 20, 1.8);
      _ring(p, 16.75, 16.75, 3.25);
    case Glyph.sliders:
      _poly(p, [4, 7.5, 6.8, 7.5]);
      _poly(p, [11.2, 7.5, 20, 7.5]);
      _ring(p, 9, 7.5, 2.2);
      _poly(p, [4, 16.5, 12.8, 16.5]);
      _poly(p, [17.2, 16.5, 20, 16.5]);
      _ring(p, 15, 16.5, 2.2);
    case Glyph.add:
      _poly(p, [12, 5, 12, 19]);
      _poly(p, [5, 12, 19, 12]);
    case Glyph.back:
      _poly(p, [14.5, 5.5, 8, 12, 14.5, 18.5]);
    case Glyph.next:
      _poly(p, [9.5, 5.5, 16, 12, 9.5, 18.5]);
    case Glyph.arrow:
      _poly(p, [5, 12, 19, 12]);
      _poly(p, [14, 7, 19, 12, 14, 17]);
    case Glyph.close:
      _poly(p, [6.5, 6.5, 17.5, 17.5]);
      _poly(p, [17.5, 6.5, 6.5, 17.5]);
    case Glyph.search:
      _ring(p, 10.5, 10.5, 6);
      _poly(p, [15, 15, 19.5, 19.5]);
    case Glyph.download:
      _poly(p, [12, 4, 12, 14.5]);
      _poly(p, [7.5, 10, 12, 14.5, 16.5, 10]);
      _poly(p, [4.5, 15, 4.5, 19.5, 19.5, 19.5, 19.5, 15]);
    case Glyph.edit:
      _poly(p, [5, 19, 5, 15.5, 15.5, 5, 19, 8.5, 8.5, 19], close: true);
      _poly(p, [13, 7.5, 16.5, 11]);
    case Glyph.calendar:
      _box(t, 4, 5.5, 20, 10, 2.5);
      _box(p, 4, 5.5, 20, 20, 2.5);
      _poly(p, [4, 10, 20, 10]);
      _poly(p, [8.5, 3.5, 8.5, 7]);
      _poly(p, [15.5, 3.5, 15.5, 7]);
      _ring(f, 8.5, 14.5, 1);
      _ring(f, 12, 14.5, 1);
      _ring(f, 15.5, 14.5, 1);
    case Glyph.note:
      _poly(p, [5, 7, 19, 7]);
      _poly(p, [5, 12, 19, 12]);
      _poly(p, [5, 17, 13, 17]);
    case Glyph.eye:
      p.moveTo(2.5, 12);
      p.quadraticBezierTo(12, 3, 21.5, 12);
      p.quadraticBezierTo(12, 21, 2.5, 12);
      _ring(p, 12, 12, 3);
    case Glyph.eyeOff:
      p.moveTo(2.5, 12);
      p.quadraticBezierTo(12, 3, 21.5, 12);
      p.quadraticBezierTo(12, 21, 2.5, 12);
      _ring(p, 12, 12, 3);
      _poly(p, [4.5, 4.5, 19.5, 19.5]);
    case Glyph.calculator:
      _box(t, 8, 6, 16, 9.5, 1);
      _box(p, 5, 3, 19, 21, 2.5);
      _box(p, 8, 6, 16, 9.5, 1);
      _ring(f, 9, 13.5, 0.95);
      _ring(f, 12, 13.5, 0.95);
      _ring(f, 15, 13.5, 0.95);
      _ring(f, 9, 17.5, 0.95);
      _ring(f, 12, 17.5, 0.95);
      _ring(f, 15, 17.5, 0.95);
    case Glyph.backspace:
      _poly(p, [8.5, 6, 20, 6, 20, 18, 8.5, 18, 3.5, 12], close: true);
      _poly(p, [11.5, 9.5, 16.5, 14.5]);
      _poly(p, [16.5, 9.5, 11.5, 14.5]);
    case Glyph.reset:
      _arc(p, 12, 12, 7, 210, 290);
      _poly(p, [5.5, 4.4, 5.9, 8.5, 9.9, 8]);
  }
}
